management:
  endpoints:
    web:
      exposure:
        include: "*"
  ​endpoint:
    ​health:
      ​show-details: always
spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
