resources:
- name: app_sources
  type: git
  source:
    uri: https://github.com/wolfoo2931/concourse-ci-hello-world.git

jobs:
- name: simple-deploy
  plan:
  - get: app_sources
  - task: list-repo-content
    config:
      platform: linux
      inputs:
      - name: app_sources
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: sh
        args:
        - -exc
        - |
          ls -R ./app_sources