= Introduction: Labs Setup

Welcome to the lab! Here you will find a collection of exercises and accompanying source-code.

== Overview

This workshop contains a number of lab folders meant to be worked through in numerical order - as each exercise builds upon the last. There is also a _samples_ directory, containing completed applications.

Your workspace is the *my_work* folder. If you get stuck implementing any of the labs, *solutions* are available for your perusal.

== PCF Environment Access

This workshop assumes participants will be interacting with PCF One.  Depending on the client and environment, ask the instuctor for an alternate CF API endpoint and/or url for the Apps Manager UI.

=== Account set up

. If you do not have an account yet, please ask the instructor for one.

== installations

The following tools are needed for the labs:

cf cli: https://github.com/cloudfoundry/cli/releases
Docker: https://docs.docker.com/docker-for-mac/install/
kubectl: https://network.pivotal.io/products/pivotal-container-service
pks cli: https://network.pivotal.io/products/pivotal-container-service
OpenJDK 11: `brew cask install adoptopenjdk11`
InteliJ Community Edition: https://www.jetbrains.com/idea/download
Lombok plugin for InteliJ: https://plugins.jetbrains.com/plugin/6317-lombok

=== Target the Environment

. Set the API target for the CLI (set appropriate end point for your environment) and login:
+
----
$ cf api https://api.run.pcfone.io
$ cf login
----
+
Enter your account username and password, then select an org and space.

== Apps Manager UI

. An alternative to installing the CF CLI is via your PCF Apps Manager interface.

. Navigate in a web browser to (depending on environment):
+
----
https://apps.run.pcfone.io
----

. Login to the interface with your email and password
+
-> The password will be supplied to you by the instructor

. Click the 'Tools' link, and download the CLI matching your operating system
