= 02. Enhancing Boot Application with Metrics

== Set up the Actuator

Spring Boot includes a number of additional features to help you monitor and manage your application when it’s pushed to production. These features are added by adding _spring-boot-starter-actuator_ to the classpath.  Our initial project setup already included it as a dependency.

. Verify the Spring Boot Actuator dependency the in following file: *cloud-native-spring/build.gradle* You should see the following dependency in the list:
+
[source,groovy]
---------------------------------------------------------------------
dependencies {
    implementation('org.springframework.boot:spring-boot-starter-actuator')
    // other dependencies omitted
}

---------------------------------------------------------------------
. Run the application again using `./gradlew bootRun` and then check the application's metrics at http://localhost:8080/actuator.
. Stop the application by typing *Ctrl+C*.

+
By default Spring Boot does not expose all the management endpoints (which is a good thing!).  Though you wouldn't want to expose all of them in production, we'll do so in this sample app to make demonstration a bit easier and simpler.

. Add the following properties to *cloud-native-spring/src/main/resources/application.yml*.
+
[source,yml]
---------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
---------------------------------------------------------------------

. Run the updated application
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------
+
Try out the following endpoints. The output is omitted here because it can be quite large:
+
curl http://localhost:8080/actuator/health
+
-> Displays Application and Datasource health information.  This can be customized based on application functionality, which we'll do later.
+
curl http://localhost:8080/actuator/beans
+
-> Displays all of the beans in the Spring context.
+
curl http://localhost:8080/actuator/configprops
+
-> Displays a collated list of all @ConfigurationProperties.
+
curl http://localhost:8080/actuator/env
+
-> Displays the application’s shell environment as well as all Java system properties.
+
curl http://localhost:8080/actuator/mappings
+
-> Displays all URI request mappings and the controller methods to which they are mapped.
+
curl http://localhost:8080/actuator/threaddump
+
-> Displays a thread dump of the currently running application in JSON format.
+
curl http://localhost:8080/actuator/heapdump
+
-> Downloads a heap dump that you can import into a JVM profiler such as JProfiler.
+
curl http://localhost:8080/actuator/httptrace
+
-> Displays trace information (by default the last few HTTP requests).
+

. Stop the _cloud-native-spring_ application.

== Include Version Control Info

Spring Boot provides an endpoint (http://localhost:8080/actuator/info) that allows the exposure of arbitrary metadata. By default, it is empty.

One thing that _actuator_ does well is expose information about the specific build and version control coordinates for a given deployment.

. Edit the following file: *cloud-native-spring/build.gradle* Add the https://github.com/n0mer/gradle-git-properties[gradle-git-properties] plugin to your Gradle build.
+
First, you'll need to be able to resolve the plugin so add the following to the _plugins{}_ section
+
[source,groovy]
---------------------------------------------------------------------
plugins {
    id 'com.gorylenko.gradle-git-properties' version '2.2.0'
}
---------------------------------------------------------------------

You'll also configure the plugin by adding a _gitProperties{}_ block.
+
[source,groovy]
---------------------------------------------------------------------
gitProperties {
    dateFormat = "yyyy-MM-dd'T'HH:mmZ"
    dateFormatTimeZone = "UTC"
    dotGitDirectory = "${project.rootDir}/../../.."
}
---------------------------------------------------------------------
-> Note too that we are updating the path to the _.git_ directory.
+
The effect of all this configuration is that the _gradle-git-properties_ plugin adds Git branch and commit coordinates to the */actuator/info* endpoint.

. Run the _cloud-native-spring_ application:
+
  gradle clean bootRun

. Let's verify that Git commit information is now included
+
[source,bash]
---------------------------------------------------------------------
curl http://localhost:8080/actuator/info
---------------------------------------------------------------------
+
[source,json]
---------------------------------------------------------------------
{
    "git": {
        "commit": {
            "time": "2017-09-07T13:52+0000",
            "id": "3393f74"
        },
        "branch": "master"
    }
}
---------------------------------------------------------------------

. Stop the _cloud-native-spring_ application
+
*What Just Happened?*
+
We have mapped Gradle properties into the `/actuator/info` endpoint.
+
Read more about exposing data in the `/actuator/info` endpoint link:https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready[here]

== Health Indicators

Spring Boot provides an endpoint http://localhost:8080/actuator/health that exposes various health indicators that describe the health of the given application.

Normally, the `/actuator/health` endpoint will only expose an UP or DOWN value.

[source,json]
---------------------------------------------------------------------
{
  "status": "UP"
}
---------------------------------------------------------------------

We want to expose more detail about the health and well-being of the application, so we're going to need a bit more configuration to `cloud-native-spring/src/main/resources/application.yml`, underneath the `management` prefix, add:

[source,yml]
---------------------------------------------------------------------
  endpoint:
    health:
      show-details: always
---------------------------------------------------------------------

. Run the cloud-native-spring application:
+
[source,bash]
---------------------------------------------------------------------
gradle bootRun
---------------------------------------------------------------------

. Use curl to verify the output of the health endpoint
+
[source,bash]
---------------------------------------------------------------------
curl http://localhost:8080/actuator/health
---------------------------------------------------------------------
+
Out of the box is a _DiskSpaceHealthIndicator_ that monitors health in terms of available disk space. Would your Ops team like to know if the app is close to running out of disk space? DiskSpaceHealthIndicator can be customized via _DiskSpaceHealthIndicatorProperties_. For instance, setting a different threshold for when to report the status as DOWN.
+
[source,json]
---------------------------------------------------------------------
{
    "status": "UP",
    "details": {
        "diskSpace": {
            "status": "UP",
            "details": {
                "total": 499963170816,
                "free": 375287070720,
                "threshold": 10485760
            }
        },
        "db": {
            "status": "UP",
            "details": {
                "database": "H2",
                "hello": 1
            }
        }
    }
}
---------------------------------------------------------------------

. Stop the cloud-native-spring application.

== Metrics

Spring Boot provides an endpoint http://localhost:8080/actuator/metrics that exposes several automatically collected metrics for your application. It also allows for the creation of custom metrics.

. Browse to http://localhost:8080/actuator/metrics. Review the metrics exposed.
+
[source,json]
---------------------------------------------------------------------
{
    "names": [
        "jvm.memory.max",
        "http.server.requests",
        "jdbc.connections.active",
        "process.files.max",
        "jvm.gc.memory.promoted",
        "tomcat.cache.hit",
        "system.load.average.1m",
        "tomcat.cache.access",
        "jvm.memory.used",
        "jvm.gc.max.data.size",
        "jdbc.connections.max",
        "jdbc.connections.min",
        "jvm.gc.pause",
        "jvm.memory.committed",
        "system.cpu.count",
        "logback.events",
        "tomcat.global.sent",
        "jvm.buffer.memory.used",
        "tomcat.sessions.created",
        "jvm.threads.daemon",
        "system.cpu.usage",
        "jvm.gc.memory.allocated",
        "tomcat.global.request.max",
        "hikaricp.connections.idle",
        "hikaricp.connections.pending",
        "tomcat.global.request",
        "tomcat.sessions.expired",
        "hikaricp.connections",
        "jvm.threads.live",
        "jvm.threads.peak",
        "tomcat.global.received",
        "hikaricp.connections.active",
        "hikaricp.connections.creation",
        "process.uptime",
        "tomcat.sessions.rejected",
        "process.cpu.usage",
        "tomcat.threads.config.max",
        "jvm.classes.loaded",
        "hikaricp.connections.max",
        "hikaricp.connections.min",
        "jvm.classes.unloaded",
        "tomcat.global.error",
        "tomcat.sessions.active.current",
        "tomcat.sessions.alive.max",
        "jvm.gc.live.data.size",
        "tomcat.servlet.request.max",
        "hikaricp.connections.usage",
        "tomcat.threads.current",
        "tomcat.servlet.request",
        "hikaricp.connections.timeout",
        "process.files.open",
        "jvm.buffer.count",
        "jvm.buffer.total.capacity",
        "tomcat.sessions.active.max",
        "hikaricp.connections.acquire",
        "tomcat.threads.busy",
        "process.start.time",
        "tomcat.servlet.error"
    ]
}
---------------------------------------------------------------------
. Browse to http://localhost:8080/actuator/metrics/jvm.memory.used to see how much memory is currently being used.

. Stop the cloud-native-spring application.

