:compat-mode:
= 05. Adding Persistence to our Boot Application

In this lab we'll utilize Spring Boot, Spring Data, and Spring Data REST to create a fully-functional hypermedia-driven RESTful web service. Along the way we'll take a brief look at https://flywaydb.org[Flyway] which can help us manage updates to database schema and data.

== Create a Hypermedia-Driven RESTful Web Service with Spring Data REST (using JPA)

This application will allow us to create, read update and delete records in an http://www.h2database.com/html/quickstart.html[in-memory] relational repository. We'll continue building upon the Spring Boot application we built out in Lab 1.  The first stereotype we will need is the domain model itself, which is `City`.

== Add the domain object - City

. Create the package `io.pivotal.domain` and in that package create the class `City`. Into that file you can paste the following source code, which represents cities based on postal codes, global coordinates, etc:
+
[source, java, numbered]
---------------------------------------------------------------------
package io.pivotal.domain;

@Data
@Entity
@Table(name="city")
public class City implements Serializable {
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String county;

    @Column(nullable = false)
    private String stateCode;

    @Column(nullable = false)
    private String postalCode;

    @Column
    private String latitude;

    @Column
    private String longitude;

}

---------------------------------------------------------------------
+
Notice that we're using http://docs.oracle.com/javaee/6/tutorial/doc/bnbpz.html[JPA] annotations on the class and its fields. We're also employing https://projectlombok.org/features/all[Lombok], so we don't have to write a bunch of boilerplate code (e.g., getter and setter methods).  You'll need to use your IDE's features to add the appropriate import statements.
+
-> Hint: imports should start with `javax.persistence` and `lombok`

. Create the package +io.pivotal.repositories+ and in that package create the interface +CityRepository+. Paste the following code and add appropriate imports:
+
[source,java]
---------------------------------------------------------------------
package io.pivotal.repositories;

@RepositoryRestResource(collectionResourceRel = "cities", path = "cities")
public interface CityRepository extends PagingAndSortingRepository<City, Long> {
}
---------------------------------------------------------------------
+
You’ll need to use your IDE’s features to add the appropriate import statements.
+
-> Hint: imports should start with `org.springframework.data.rest.core.annotation` and `org.springframework.data.repository`

== Use Flyway to manage schema

. Edit _build.gradle_ and add the following dependencies within the _dependencies {}_ block
+
[source,bash]
---------------------------------------------------------------------
implementation('org.flywaydb:flyway-core:5.2.4')
implementation('com.zaxxer:HikariCP:3.3.0')
---------------------------------------------------------------------

. Create a new file named +V1_0__init_database.sql+ underneath _devops-workshop/labs/my_work/cloud-native-spring/src/main/resources/db/migration_, add the following lines and save.
+
[source,bash]
---------------------------------------------------------------------
CREATE TABLE city (
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR(100) NOT NULL,
   COUNTY VARCHAR(100) NOT NULL,
   STATE_CODE VARCHAR(10) NOT NULL,
   POSTAL_CODE VARCHAR(10) NOT NULL,
   LATITUDE VARCHAR(15) NOT NULL,
   LONGITUDE VARCHAR(15) NOT NULL
);
---------------------------------------------------------------------
+
Spring Boot comes with out-of-the-box https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-execute-flyway-database-migrations-on-startup[integration] support for https://flywaydb.org/documentation/plugins/springboot[Flyway].  When we start the application it will execute a versioned https://flywaydb.org/documentation/migrations#sql-based-migrations[SQL migration] that will create a new table in the database.

. Add the following lines to _devops-workshop/labs/my_work/cloud-native-spring/src/main/resources/application.yml_
+
[source,bash]
---------------------------------------------------------------------
spring:
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
---------------------------------------------------------------------
https://github.com/brettwooldridge/HikariCP/blob/dev/README.md[Hikari] is a database connection pool implementation. We are limiting the number of database connections an individual application instance may consume.

== Run the _cloud-native-spring_ Application

. Return to the Terminal session you opened previously

. Run the application
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------

. Access the application using +curl+ or your web browser using the newly added REST repository endpoint at http://localhost:8080/cities. You'll see that the primary endpoint automatically exposes the ability to page, size, and sort the response JSON.
+
[source,bash]
---------------------------------------------------------------------
curl http://localhost:8080/cities

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/hal+json;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 28 Apr 2016 14:44:06 GMT

{
  "_embedded" : {
    "cities" : [ ]
  },
  "_links" : {
    "self" : {
      "href" : "http://localhost:8080/cities"
    },
    "profile" : {
      "href" : "http://localhost:8080/profile/cities"
    }
  },
  "page" : {
    "size" : 20,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
---------------------------------------------------------------------

. To exit the application, type *Ctrl-C*.

So what have you done? Created four small classes, modified a build file, added some configuration and SQL migration scripts, resulting in a fully-functional REST microservice. The application's +DataSource+ is created automatically by Spring Boot using the in-memory database because *no other +DataSource+ was detected in the project*.

Next we'll import some data.

== Importing Data

. Copy the https://raw.githubusercontent.com/Pivotal-Field-Engineering/devops-workshop/master/labs/import.sql[import.sql] file found in `devops-workshop/labs/` to `devops-workshop/labs/my_work/cloud-native-spring/src/main/resources/db/migration`. Rename the file to be +V1_1__seed_data.sql+. (This is a small subset of a larger dataset containing all of the postal codes in the United States and its territories).

. Restart the application.
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------

. Access the application again. Notice the appropriate hypermedia is included for +next+, +previous+, and +self+. You can also select pages and page size by utilizing +?size=n&page=n+ on the URL string. Finally, you can sort the data utilizing +?sort=fieldName+ (replace fieldName with a cities attribute).
+
[source,bash]
---------------------------------------------------------------------
curl http://localhost:8080/cities

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 19:59:58 GMT

{
  "_links" : {
    "next" : {
      "href" : "http://localhost:8080/cities?page=1&size=20"
    },
    "self" : {
      "href" : "http://localhost:8080/cities{?page,size,sort}",
      "templated" : true
    }
  },
  "_embedded" : {
    "cities" : [ {
      "name" : "HOLTSVILLE",
      "county" : "SUFFOLK",
      "stateCode" : "NY",
      "postalCode" : "00501",
      "latitude" : "+40.922326",
      "longitude" : "-072.637078",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/1"
        }
      }
    },

    // ...

    {
      "name" : "CASTANER",
      "county" : "LARES",
      "stateCode" : "PR",
      "postalCode" : "00631",
      "latitude" : "+18.269187",
      "longitude" : "-066.864993",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/cities/20"
        }
      }
    } ]
  },
  "page" : {
    "size" : 20,
    "totalElements" : 42741,
    "totalPages" : 2138,
    "number" : 0
  }
}
---------------------------------------------------------------------

. Try the following URL Paths with +curl+ to see how the application behaves:
+
http://localhost:8080/cities?size=5
+
http://localhost:8080/cities?size=5&page=3
+
http://localhost:8080/cities?sort=postalCode,desc

Next we'll add searching capabilities.

== Adding Search

. Let's add some additional finder methods to +CityRepository+:
+
[source,java]
---------------------------------------------------------------------
@RestResource(path = "name", rel = "name")
Page<City> findByNameIgnoreCase(@Param("q") String name, Pageable pageable);

@RestResource(path = "nameContains", rel = "nameContains")
Page<City> findByNameContainsIgnoreCase(@Param("q") String name, Pageable pageable);

@RestResource(path = "state", rel = "state")
Page<City> findByStateCodeIgnoreCase(@Param("q") String stateCode, Pageable pageable);

@RestResource(path = "postalCode", rel = "postalCode")
Page<City> findByPostalCode(@Param("q") String postalCode, Pageable pageable);

@Query(value ="select c from City c where c.stateCode = :stateCode")
Page<City> findByStateCode(@Param("stateCode") String stateCode, Pageable pageable);
---------------------------------------------------------------------
+
-> Hint: imports should start with `org.springframework.data.domain`, `org.springframework.data.rest.core.annotation`, `org.springframework.data.repository.query`, and `org.springframework.data.jpa.repository`

. Run the application
+
[source,bash]
---------------------------------------------------------------------
gradle clean bootRun
---------------------------------------------------------------------

. Access the application again. Notice that hypermedia for a new +search+ endpoint has appeared.
+
[source,bash]
---------------------------------------------------------------------
curl http://localhost:8080/cities

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 20:33:52 GMT

// prior omitted
    },
    "_links": {
        "first": {
            "href": "http://localhost:8080/cities?page=0&size=20"
        },
        "self": {
            "href": "http://localhost:8080/cities{?page,size,sort}",
            "templated": true
        },
        "next": {
            "href": "http://localhost:8080/cities?page=1&size=20"
        },
        "last": {
            "href": "http://localhost:8080/cities?page=2137&size=20"
        },
        "profile": {
            "href": "http://localhost:8080/profile/cities"
        },
        "search": {
            "href": "http://localhost:8080/cities/search"
        }
    },
    "page": {
        "size": 20,
        "totalElements": 42741,
        "totalPages": 2138,
        "number": 0
    }
}
---------------------------------------------------------------------

. Access the new +search+ endpoint:
+
http://localhost:8080/cities/search
+
[source,bash]
---------------------------------------------------------------------
curl http://localhost:8080/cities/search

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-Application-Context: application
Content-Type: application/hal+json
Transfer-Encoding: chunked
Date: Tue, 27 May 2014 20:38:32 GMT

{
    "_links": {
        "postalCode": {
            "href": "http://localhost:8080/cities/search/postalCode{?q,page,size,sort}",
            "templated": true
        },
        "state": {
            "href": "http://localhost:8080/cities/search/state{?q,page,size,sort}",
            "templated": true
        },
        "nameContains": {
            "href": "http://localhost:8080/cities/search/nameContains{?q,page,size,sort}",
            "templated": true
        },
        "name": {
            "href": "http://localhost:8080/cities/search/name{?q,page,size,sort}",
            "templated": true
        },
        "findByStateCode": {
            "href": "http://localhost:8080/cities/search/findByStateCode{?stateCode,page,size,sort}",
            "templated": true
        },
        "self": {
            "href": "http://localhost:8080/cities/search"
        }
    }
}
---------------------------------------------------------------------
+
Note that we now have new search endpoints for each of the finders that we added.

. Try a few of these endpoints in https://www.getpostman.com[Postman]. Feel free to substitute your own values for the parameters.
+
http://localhost:8080/cities/search/postalCode?q=01229
+
http://localhost:8080/cities/search/name?q=Springfield
+
http://localhost:8080/cities/search/nameContains?q=West&size=1
+
-> For further details on what's possible with Spring Data JPA, consult the https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#dependencies.spring-boot[reference documentation]



