== Pushing to Cloud Foundry

. Build the application
+
[source,bash]
---------------------------------------------------------------------
gradle build
---------------------------------------------------------------------

. You should already have an application manifest, +manifest.yml+, created in Lab 1; this can be reused.  You'll want to add a timeout param so that our service has enough time to initialize with its data loading:
+
[source,yml]
---------------------------------------------------------------------
---
applications:
- name: cloud-native-spring
  random-route: true
  memory: 1024M
  instances: 1
  path: ./build/libs/cloud-native-spring-1.0-SNAPSHOT-exec.jar
  buildpacks:
  - java_buildpack_offline
  stack: cflinuxfs3
  timeout: 180 # to give time for the data to import
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
---------------------------------------------------------------------

. Push to Cloud Foundry:
+
[source,bash]
---------------------------------------------------------------------
cf push

...

Showing health and status for app cloud-native-spring in org zoo-labs / space development as cphillipson@pivotal.io...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: cloud-native-spring-apodemal-hyperboloid.cfapps.io
last uploaded: Thu Jul 28 23:29:21 UTC 2018
stack: cflinuxfs2
buildpack: java_buildpack_offline

     state     since                    cpu      memory         disk         details
#0   running   2018-07-28 04:30:22 PM   163.7%   395.7M of 1G   159M of 1G
---------------------------------------------------------------------

. Access the application at the random route provided by CF:
+
[source,bash]
---------------------------------------------------------------------
http GET https://cloud-native-spring-{random-word}.{domain}.com/cities
---------------------------------------------------------------------
+
+{random-word}+ might be something like +loquacious-eagle+ and +{domain}+ might be +cfapps.io+ if you happened to target Pivotal Web Services

. Let's stop the application momentarily as we prepare to swap out the database provider.
+
[source,bash]
---------------------------------------------------------------------
cf stop cloud-native-spring
---------------------------------------------------------------------

== Binding to a MySQL database in Cloud Foundry

. Let's create a MySQL database instance. Hopefully, you will have https://network.pivotal.io/products/pivotal-mysql[p.mysql] service available in CF Marketplace.
+
[source,bash]
---------------------------------------------------------------------
cf marketplace -s p.mysql
---------------------------------------------------------------------
+
Expected output:
+
[source,bash]
---------------------------------------------------------------------
Getting service plan information for service p.mysql as cphillipson@pivotal.io...
OK

service plan   description                                            free or paid
db-small       This plan provides a small dedicated MySQL instance.   free
---------------------------------------------------------------------

. Let's create an instance of `p.mysql` with `db-small` plan, e.g.
+
[source,bash]
---------------------------------------------------------------------
cf create-service p.mysql db-small mysql-database
---------------------------------------------------------------------
+
Expected output:
+
[source,bash]
---------------------------------------------------------------------
Creating service instance mysql-database in org zoo-labs / space development as cphillipson@pivotal.io...
OK
---------------------------------------------------------------------
+
So long as the name of the service contains `mysql` the https://dev.mysql.com/downloads/connector/j/[mysql-connector] JDBC driver will https://github.com/cloudfoundry/java-buildpack/blob/master/docs/framework-maria_db_jdbc.md#mariadb-jdbc-framework[automatically be added] as a runtime dependency.
+
However, we're going to explicitly define a runtime dependency on the MySQL JDBC driver.  Open `build.gradle` for editing and add the following to the `dependencies` section
+
[source,json]
---------------------------------------------------------------------
runtime('mysql:mysql-connector-java:8.0.15')
---------------------------------------------------------------------
+
And, of course we must rebuild and repackage the application to have the application recognize the new dependency at runtime
+
[source,bash]
---------------------------------------------------------------------
gradle build
---------------------------------------------------------------------

. Let's bind the service to the application, e.g.
+
[source,bash]
---------------------------------------------------------------------
cf bind-service cloud-native-spring mysql-database
---------------------------------------------------------------------
+
Expected output:
+
[source,bash]
---------------------------------------------------------------------
Binding service mysql-database to app cloud-native-spring in org zoo-labs / space development as cphillipson@pivotal.io...
OK
---------------------------------------------------------------------
+
-> Tip: Use `cf restage cloud-native-spring` to ensure your env variable changes take effect


. Now let's push the updated application
+
[source,bash]
---------------------------------------------------------------------
cf push cloud-native-spring
---------------------------------------------------------------------

. You may wish to observe the logs and notice that the bound MySQL database is picked up by the application, e.g.
+
[source,bash]
---------------------------------------------------------------------
cf logs cloud-native-spring --recent
---------------------------------------------------------------------
+
Sample output:
+
[source,bash]
---------------------------------------------------------------------
...
INFO 20 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.0.12.Final}
INFO 20 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
INFO 20 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
INFO 20 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
INFO 20 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
INFO 20 --- [           main] org.hibernate.tool.hbm2ddl.SchemaUpdate  : HHH000228: Running hbm2ddl schema update
...
---------------------------------------------------------------------

. You could also bind to the database directly from the `manifest.yml` file, e.g.
+
[source,yml]
---------------------------------------------------------------------
applications:
- name: cloud-native-spring
  random-route: true
  memory: 1024M
  instances: 1
  path: ./build/libs/cloud-native-spring-1.0-SNAPSHOT-exec.jar
  buildpacks:
  - java_buildpack_offline
  timeout: 180 # to give time for the data to import
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
  services:
    - mysql-database
---------------------------------------------------------------------
+
. Attempt to push the app again after making this update
+
[source,bash]
---------------------------------------------------------------------
cf push
---------------------------------------------------------------------

. Let's have a look at how we can interact with the database

Visit https://github.com/pivotal-cf/PivotalMySQLWeb[Pivotal MySQL*Web] then follow these instructions for building the application.
+
[source,bash]
---------------------------------------------------------------------
cd ..
git clone https://github.com/pivotal-cf/PivotalMySQLWeb.git
cd PivotalMySQLWeb
./mvnw -DskipTests=true package
---------------------------------------------------------------------
+
Then to prepare the application for deployment we'll create a manifest. Open an editor, create and save a file named `manifest.yml` with these contents:
+
[source,yml]
---------------------------------------------------------------------
applications:
- name: pivotal-mysqlweb
  memory: 1024M
  instances: 1
  random-route: true
  path: ./target/PivotalMySQLWeb-1.0.0-SNAPSHOT.jar
  services:
    - mysql-database
  env:
    JAVA_OPTS: -Djava.security.egd=file:///dev/urandom
---------------------------------------------------------------------
+
Of course, you'll want to deploy the application
+
[source,bash]
---------------------------------------------------------------------
cf push
---------------------------------------------------------------------
+
And once deployed, you can visit the appliation URL and log in with the default credentials `admin/cfmysqlweb`
+
Take a few moments to explore the features and see that the administrative and diagnostic functions of Pivotal MySQL*Web provide a rather simple way to interact with and keep your database instance up-to-date via an Internet browser.
