= 08. Introduction to CF CLI

So far we discussed Java, but Cloud Foundry supports all the modern, cloud-native languages. Let's deploy some simple sample apps in various languages.

- Change the working directory to be _devops-workshop/labs/samples_
+
Note the sub-directories present..
+
[source, bash]
---------------------------------------------------------------------
samples
├── dotnet-core-sample
├── go-sample
├── nodejs-sample
├── python-sample
---------------------------------------------------------------------
+

== Open Apps Manager

Go to the URL https://apps.run.pcfone.io and login with the credentials provided by your instructor.

== How to target a foundation and login

. Open a Terminal (e.g., _cmd_ or _bash_ shell)

. Target a foundation and login
----
$ cf login -a https://api.run.pcfone.io
----
+
Enter your account username and password, then select an org and space unless those were chosen for you automatically.

== How to deploy an application

. Let's take a look at the CF CLI options
+
  cf help -a

. Let's see what buildpacks are available to us
+
  cf buildpacks

. Peruse the services you can provision and bind your applications to
+
  cf marketplace

. Time to deploy an app. How about Node.js? Before running _cf push_, always inspect the _manifest.yml_ file in each directory.
+
  cd nodejs-sample
  cf push -c "node server.js"
+

Notice that PCF also _built_ the application for you before creating the container and running the app. You can also build your application locally (if you have `yarn` installed), and just provide the final artifact to PCF:
+
[source,bash]
----------------------------------------
yarn config set yarn-offline-mirror ./npm-packages-offline-cache
cp ~/.yarnrc .
rm -rf node_modules/ yarn.lock
yarn install

cf push -c "node server.js"
----------------------------------------

. Next, let's try deploying a Python app. Note that again, PCF builds the application for you:
+
[source,bash]
----------------------------------------
cd ../python-sample
cf push my_pyapp
----------------------------------------

. Rinse and repeat for .Net Core (again, built during deployment):
+
[source,bash]
----------------------------------------
cd ../dotnet-core-sample
cf push
----------------------------------------

. Now let's push a Go app. Notice there's no _manifest.yml_ in this directory. How did PCF know it's a Go app?
+
[source,bash]
----------------------------------------
cd ../go-sample
cf push awesome-go-sample
----------------------------------------

. So far we let the platform create our container images during delpoyment. But what about docker images that were already built? We can deploy those too.
+
[source,bash]
----------------------------------------
cd ../docker-sample
cf push
----------------------------------------


. Check what applications have been deployed so far
+
[source,bash]
----------------------------------------
cf apps
----------------------------------------
+
-> Take some time to visit each of the applications you've just deployed.

Open Apps Manager and review your applications from the UI:

https://apps.run.pcfone.io

Click the "View App" link on the top right side of each app's overview screen.

. Let's scale an app
+
[source,bash]
----------------------------------------
cf scale cf-nodejs -i 3
cf apps
----------------------------------------
+

Refresh the App's URL and see how _INSTANCE INDEX_ changes with each refresh.

. Let's stop an app, then check that it has indeed been stopped
+
[source,bash]
----------------------------------------
cf stop cf-nodejs
cf apps
----------------------------------------

== How to cleanup after yourself

. Finally, let's delete an app
+
[source,bash]
----------------------------------------
cf delete cf-nodejs
----------------------------------------
+
-> Repeat `cf delete` for each app you deployed.

== Where to go for more help

-> https://docs.cloudfoundry.org/cf-cli/getting-started.html[Getting Started with the CF CLI]

-> http://www.appservgrid.com/refcards/refcards/dzonerefcards/rc207-010d-cloud-foundry.pdf[Cloud Foundry Cheat Sheet]
