= Introduction to CF CLI

- Change the working directory to be _devops-workshop/labs/samples_
+
Note the sub-directories present..
+
[source, bash]
---------------------------------------------------------------------
samples
├── dotnet-core-sample
├── go-sample
├── nodejs-sample
├── python-sample
---------------------------------------------------------------------
+
-> If you want to be able to deploy these samples you must have _Go_, _Node_, _.Net Core_, and _Python_ installed.

== How to target a foundation and login

. Open a Terminal (e.g., _cmd_ or _bash_ shell)

. Target a foundation and login
+
*PCFOne*
+
----
$ cf login -a https://api.run.pcfone.io
----
+
Enter your account username and password, then select an org and space.

== How to deploy an application

. Let's take a look at the CF CLI options
+
  cf help -a

. Let's see what buildpacks are available to us
+
  cf buildpacks

. Peruse the services you can provision and bind your applications to
+
  cf marketplace

. Time to deploy an app. How about Node.js? Before running _cf push_, always inspect the _manifest.yml_ file in each directory.
+
  cd nodejs-sample
  cf push -c "node server.js"
+

Notice that PCF also _built_ the application for you before creating the container and running the app. You can also build your application locally and just provide the final artifact to PCF:
+
  yarn config set yarn-offline-mirror ./npm-packages-offline-cache
  cp ~/.yarnrc .
  rm -rf node_modules/ yarn.lock
  yarn install

  cf push -c "node server.js"


. Next, let's try deploying a Python app. Note that again, PCF builds the application for you:
+
  cd ../python-sample
  cf push my_pyapp

. Rinse and repeat for .Net Core (again, built during deployment):
+
  cd ../dotnet-core-sample
  cf push

. Now let's push a Go app. Notice there's no _manifest.yml_ in this directory. How did PCF know it's a Go app?
+
  cd ../go-sample
  cf push awesome-go-app -m 64M --random-route

. Check what applications have been deployed so far
+
  cf apps
+
-> Take some time to visit each of the applications you've just deployed.

Open Apps Manager and review your applications from the UI:

https://apps.run.pcfone.io

. Let's scale an app
+
  cf scale cf-nodejs -i 3
  cf apps
+
Refresh the App's URL and see how _INSTANCE INDEX_ changes with each refresh.

. Let's stop an app, then check that it has indeed been stopped
+
  cf stop cf-nodejs
  cf apps

== How to cleanup after yourself

. Finally, let's delete an app
+
  cf delete cf-nodejs
+
-> Repeat `cf delete` for each app you deployed.

== Where to go for more help

-> https://docs.cloudfoundry.org/cf-cli/getting-started.html[Getting Started with the CF CLI]

-> http://www.appservgrid.com/refcards/refcards/dzonerefcards/rc207-010d-cloud-foundry.pdf[Cloud Foundry Cheat Sheet]